### PR TITLE
fix-flaky

### PR DESCRIPTION
**Pull request by wang3820**
### Flakiness
**Nondex** was used to check and locate the flakiness in the test. The test can be reproduced using the following command:
```shell
mvn install -pl support/cdi -am -DskipTests
mvn -pl support/cdi test -Dtest=org.apache.shiro.cdi.AnnotatedTypeWrapperTest#removeAnnotations
mvn -pl support/cdi edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.apache.shiro.cdi.AnnotatedTypeWrapperTest#removeAnnotations
``` 

### Issue
The test checks that if there is no `Annotation` in the `RequiresGuest` class and there is `Annotation` in `SessionScoped` class. It retrieves these classes by calling `getDeclaredAnnotations` method and fix indexing on the array returned. This creates the problem. Here is the implementation of  `getDeclaredAnnotations` :
```java
public Annotation[] getDeclaredAnnotations() {
     return AnnotationParser.toArray(this.annotationData().declaredAnnotations);
}
// this.annotationData().declaredAnnotationsdeclaredAnnotations is a map
Map<Class<? extends Annotation>, Annotation> declaredAnnotations = ....
```
Since the array is created from a hashmap, the order of elements in the output of `getDeclaredAnnotations` is not determinstic. Therefore, the fix indexing creates flakiness.

## Fix
Since only `SessionScoped`  and `RequiresGuest` are tested, those 2 classes are specificly extracted from the array instead of using indexing.

### CODE REVIEW

**Comment by deekshacheruku** [comment]
"Since only SessionScoped and RequiresGuest are tested, those 2 classes are specificly extracted from the array instead of using indexing." Is there any documentation which states that only these two classes are extracted from the Array?

**Comment by wang3820** [comment]
Hi, thanks for the comment. Based on the original test, only these 2 classes are checked by assertion.
```Java
        assertEquals(3, wrapper.getAnnotations().size());
        assertFalse(wrapper.isAnnotationPresent(RequiresGuest.class));
        assertTrue(wrapper.isAnnotationPresent(SessionScoped.class));
```

**Comment by kavvya97** [comment]
1. Add Link to nondex link to repo
2. I am not understanding why 2 assertion statements have been added. I am not sure why these additional assertion statements are required. can you explain more?

**Comment by wang3820** [comment]
> 1. Add Link to nondex link to repo
> 2. I am not understanding why 2 assertion statements have been added. I am not sure why these additional assertion statements are required. can you explain more?

Thanks for your feedback. 
1. Do you mind explaining what do you mean by adding link to nondex link? 
2. The 2 assertions makes sure that the 2 tested classes are returned by `getDeclaredAnnotations`.

**Comment by zzjas** [comment]
Please rebase. Can't see what's changed.

**Pull request merged**
